---
roles:
# From: https://github.com/ansible-community/ansible-build-data/blob/main/8/ansible-8.1.0.yaml
collections:
- name: amazon.aws
  source: https://galaxy.ansible.com
  version: 6.1.0
- name: ansible.netcommon
  source: https://galaxy.ansible.com
  version: 5.1.1
- name: ansible.posix
  source: https://galaxy.ansible.com
  version: 1.5.4
- name: ansible.utils
  source: https://galaxy.ansible.com
  version: 2.10.3
- name: awx.awx
  source: https://galaxy.ansible.com
  version: 22.3.0
- name: cloud.common
  source: https://galaxy.ansible.com
  version: 2.1.3
- name: community.aws
  source: https://galaxy.ansible.com
  version: 6.0.0
- name: community.crypto
  source: https://galaxy.ansible.com
  version: 2.14.0
- name: community.digitalocean
  source: https://galaxy.ansible.com
  version: 1.23.0
- name: community.dns
  source: https://galaxy.ansible.com
  version: 2.5.6
- name: community.docker
  source: https://galaxy.ansible.com
  version: 3.4.8
- name: community.general
  source: https://galaxy.ansible.com
  version: 7.1.0
- name: community.google
  source: https://galaxy.ansible.com
  version: 1.0.0
- name: community.grafana
  source: https://galaxy.ansible.com
  version: 1.5.4
- name: community.hashi_vault
  source: https://galaxy.ansible.com
  version: 5.0.0
- name: community.libvirt
  source: https://galaxy.ansible.com
  version: 1.2.0
- name: community.mongodb
  source: https://galaxy.ansible.com
  version: 1.6.0
- name: community.mysql
  source: https://galaxy.ansible.com
  version: 3.7.2
- name: community.network
  source: https://galaxy.ansible.com
  version: 5.0.0
- name: community.okd
  source: https://galaxy.ansible.com
  version: 2.3.0
- name: community.postgresql
  source: https://galaxy.ansible.com
  version: 2.4.2
- name: community.proxysql
  source: https://galaxy.ansible.com
  version: 1.5.1
- name: community.rabbitmq
  source: https://galaxy.ansible.com
  version: 1.2.3
- name: community.routeros
  source: https://galaxy.ansible.com
  version: 2.8.2
- name: community.sops
  source: https://galaxy.ansible.com
  version: 1.6.2
- name: containers.podman
  source: https://galaxy.ansible.com
  version: 1.10.2
- name: frr.frr
  source: https://galaxy.ansible.com
  version: 2.0.2
- name: google.cloud
  source: https://galaxy.ansible.com
  version: 1.1.3
- name: grafana.grafana
  source: https://galaxy.ansible.com
  version: 2.0.0
- name: kubernetes.core
  source: https://galaxy.ansible.com
  version: 2.4.0
- name: netbox.netbox
  source: https://galaxy.ansible.com
  version: 3.13.0
- name: openvswitch.openvswitch
  source: https://galaxy.ansible.com
  version: 2.1.1
- name: ovirt.ovirt
  source: https://galaxy.ansible.com
  version: 3.1.2
- name: theforeman.foreman
  source: https://galaxy.ansible.com
  version: 3.11.0
- name: vyos.vyos
  source: https://galaxy.ansible.com
  version: 4.1.0
