---
roles:
# From: https://github.com/ansible-community/ansible-build-data/blob/main/9/ansible-9.4.0.yaml
collections:
- name: amazon.aws
  source: https://galaxy.ansible.com
  version: 7.4.0
- name: ansible.netcommon
  source: https://galaxy.ansible.com
  version: 5.3.0
- name: ansible.posix
  source: https://galaxy.ansible.com
  version: 1.5.4
- name: ansible.utils
  source: https://galaxy.ansible.com
  version: 2.12.0
- name: ansible.windows
  source: https://galaxy.ansible.com
  version: 2.3.0
- name: arista.eos
  source: https://galaxy.ansible.com
  version: 6.2.2
- name: awx.awx
  source: https://galaxy.ansible.com
  version: 23.9.0
- name: azure.azcollection
  source: https://galaxy.ansible.com
  version: 1.19.0
- name: check_point.mgmt
  source: https://galaxy.ansible.com
  version: 5.2.3
- name: chocolatey.chocolatey
  source: https://galaxy.ansible.com
  version: 1.5.1
- name: cisco.aci
  source: https://galaxy.ansible.com
  version: 2.8.0
- name: cisco.asa
  source: https://galaxy.ansible.com
  version: 4.0.3
- name: cisco.dnac
  source: https://galaxy.ansible.com
  version: 6.13.1
- name: cisco.intersight
  source: https://galaxy.ansible.com
  version: 2.0.7
- name: cisco.ios
  source: https://galaxy.ansible.com
  version: 5.3.0
- name: cisco.iosxr
  source: https://galaxy.ansible.com
  version: 6.1.1
- name: cisco.ise
  source: https://galaxy.ansible.com
  version: 2.8.0
- name: cisco.meraki
  source: https://galaxy.ansible.com
  version: 2.17.2
- name: cisco.mso
  source: https://galaxy.ansible.com
  version: 2.5.0
- name: cisco.nxos
  source: https://galaxy.ansible.com
  version: 5.3.0
- name: cisco.ucs
  source: https://galaxy.ansible.com
  version: 1.10.0
- name: cloud.common
  source: https://galaxy.ansible.com
  version: 2.1.4
- name: cloudscale_ch.cloud
  source: https://galaxy.ansible.com
  version: 2.3.1
- name: community.aws
  source: https://galaxy.ansible.com
  version: 7.1.0
- name: community.azure
  source: https://galaxy.ansible.com
  version: 2.0.0
- name: community.ciscosmb
  source: https://galaxy.ansible.com
  version: 1.0.7
- name: community.crypto
  source: https://galaxy.ansible.com
  version: 2.18.0
- name: community.digitalocean
  source: https://galaxy.ansible.com
  version: 1.26.0
- name: community.dns
  source: https://galaxy.ansible.com
  version: 2.8.3
- name: community.docker
  source: https://galaxy.ansible.com
  version: 3.8.1
- name: community.general
  source: https://galaxy.ansible.com
  version: 8.5.0
- name: community.grafana
  source: https://galaxy.ansible.com
  version: 1.8.0
- name: community.hashi_vault
  source: https://galaxy.ansible.com
  version: 6.2.0
- name: community.hrobot
  source: https://galaxy.ansible.com
  version: 1.9.1
- name: community.library_inventory_filtering_v1
  source: https://galaxy.ansible.com
  version: 1.0.0
- name: community.libvirt
  source: https://galaxy.ansible.com
  version: 1.3.0
- name: community.mongodb
  source: https://galaxy.ansible.com
  version: 1.7.2
- name: community.mysql
  source: https://galaxy.ansible.com
  version: 3.9.0
- name: community.network
  source: https://galaxy.ansible.com
  version: 5.0.2
- name: community.okd
  source: https://galaxy.ansible.com
  version: 2.3.0
- name: community.postgresql
  source: https://galaxy.ansible.com
  version: 3.4.0
- name: community.proxysql
  source: https://galaxy.ansible.com
  version: 1.5.1
- name: community.rabbitmq
  source: https://galaxy.ansible.com
  version: 1.2.3
- name: community.routeros
  source: https://galaxy.ansible.com
  version: 2.14.0
- name: community.sap
  source: https://galaxy.ansible.com
  version: 2.0.0
- name: community.sap_libs
  source: https://galaxy.ansible.com
  version: 1.4.2
- name: community.sops
  source: https://galaxy.ansible.com
  version: 1.6.7
- name: community.vmware
  source: https://galaxy.ansible.com
  version: 4.2.0
- name: community.windows
  source: https://galaxy.ansible.com
  version: 2.2.0
- name: community.zabbix
  source: https://galaxy.ansible.com
  version: 2.3.1
- name: containers.podman
  source: https://galaxy.ansible.com
  version: 1.12.0
- name: cyberark.conjur
  source: https://galaxy.ansible.com
  version: 1.2.2
- name: cyberark.pas
  source: https://galaxy.ansible.com
  version: 1.0.25
- name: dellemc.enterprise_sonic
  source: https://galaxy.ansible.com
  version: 2.4.0
- name: dellemc.openmanage
  source: https://galaxy.ansible.com
  version: 8.7.0
- name: dellemc.powerflex
  source: https://galaxy.ansible.com
  version: 2.2.0
- name: dellemc.unity
  source: https://galaxy.ansible.com
  version: 1.7.1
- name: f5networks.f5_modules
  source: https://galaxy.ansible.com
  version: 1.28.0
- name: fortinet.fortimanager
  source: https://galaxy.ansible.com
  version: 2.4.0
- name: fortinet.fortios
  source: https://galaxy.ansible.com
  version: 2.3.5
- name: frr.frr
  source: https://galaxy.ansible.com
  version: 2.0.2
- name: gluster.gluster
  source: https://galaxy.ansible.com
  version: 1.0.2
- name: google.cloud
  source: https://galaxy.ansible.com
  version: 1.3.0
- name: grafana.grafana
  source: https://galaxy.ansible.com
  version: 2.2.5
- name: hetzner.hcloud
  source: https://galaxy.ansible.com
  version: 2.5.0
- name: hpe.nimble
  source: https://galaxy.ansible.com
  version: 1.1.4
- name: ibm.qradar
  source: https://galaxy.ansible.com
  version: 2.1.0
- name: ibm.spectrum_virtualize
  source: https://galaxy.ansible.com
  version: 2.0.0
- name: ibm.storage_virtualize
  source: https://galaxy.ansible.com
  version: 2.3.1
- name: infinidat.infinibox
  source: https://galaxy.ansible.com
  version: 1.4.3
- name: infoblox.nios_modules
  source: https://galaxy.ansible.com
  version: 1.6.1
- name: inspur.ispim
  source: https://galaxy.ansible.com
  version: 2.2.0
- name: inspur.sm
  source: https://galaxy.ansible.com
  version: 2.3.0
- name: junipernetworks.junos
  source: https://galaxy.ansible.com
  version: 5.3.1
- name: kubernetes.core
  source: https://galaxy.ansible.com
  version: 2.4.2
- name: lowlydba.sqlserver
  source: https://galaxy.ansible.com
  version: 2.3.2
- name: microsoft.ad
  source: https://galaxy.ansible.com
  version: 1.5.0
- name: netapp.aws
  source: https://galaxy.ansible.com
  version: 21.7.1
- name: netapp.azure
  source: https://galaxy.ansible.com
  version: 21.10.1
- name: netapp.cloudmanager
  source: https://galaxy.ansible.com
  version: 21.22.1
- name: netapp.elementsw
  source: https://galaxy.ansible.com
  version: 21.7.0
- name: netapp.ontap
  source: https://galaxy.ansible.com
  version: 22.10.0
- name: netapp.storagegrid
  source: https://galaxy.ansible.com
  version: 21.12.0
- name: netapp.um_info
  source: https://galaxy.ansible.com
  version: 21.8.1
- name: netapp_eseries.santricity
  source: https://galaxy.ansible.com
  version: 1.4.0
- name: netbox.netbox
  source: https://galaxy.ansible.com
  version: 3.17.0
- name: ngine_io.cloudstack
  source: https://galaxy.ansible.com
  version: 2.3.0
- name: ngine_io.exoscale
  source: https://galaxy.ansible.com
  version: 1.1.0
- name: openstack.cloud
  source: https://galaxy.ansible.com
  version: 2.2.0
- name: openvswitch.openvswitch
  source: https://galaxy.ansible.com
  version: 2.1.1
- name: ovirt.ovirt
  source: https://galaxy.ansible.com
  version: 3.2.0
- name: purestorage.flasharray
  source: https://galaxy.ansible.com
  version: 1.27.0
- name: purestorage.flashblade
  source: https://galaxy.ansible.com
  version: 1.16.0
- name: purestorage.fusion
  source: https://galaxy.ansible.com
  version: 1.6.1
- name: sensu.sensu_go
  source: https://galaxy.ansible.com
  version: 1.14.0
- name: splunk.es
  source: https://galaxy.ansible.com
  version: 2.1.2
- name: t_systems_mms.icinga_director
  source: https://galaxy.ansible.com
  version: 2.0.1
- name: telekom_mms.icinga_director
  source: https://galaxy.ansible.com
  version: 1.35.0
- name: theforeman.foreman
  source: https://galaxy.ansible.com
  version: 3.15.0
- name: vmware.vmware_rest
  source: https://galaxy.ansible.com
  version: 2.3.1
- name: vultr.cloud
  source: https://galaxy.ansible.com
  version: 1.12.1
- name: vyos.vyos
  source: https://galaxy.ansible.com
  version: 4.1.0
- name: wti.remote
  source: https://galaxy.ansible.com
  version: 1.0.5
