---
roles:
# From: https://github.com/ansible-community/ansible-build-data/blob/main/9/ansible-10.3.0.yaml
collections:
- name: amazon.aws
  source: https://galaxy.ansible.com
  version: 8.1.0
- name: ansible.netcommon
  source: https://galaxy.ansible.com
  version: 6.1.3
- name: ansible.posix
  source: https://galaxy.ansible.com
  version: 1.5.4
- name: ansible.utils
  source: https://galaxy.ansible.com
  version: 4.1.0
- name: awx.awx
  source: https://galaxy.ansible.com
  version: 24.6.1
- name: cloud.common
  source: https://galaxy.ansible.com
  version: 3.0.0
- name: community.aws
  source: https://galaxy.ansible.com
  version: 8.0.0
- name: community.crypto
  source: https://galaxy.ansible.com
  version: 2.21.1
- name: community.digitalocean
  source: https://galaxy.ansible.com
  version: 1.26.0
- name: community.dns
  source: https://galaxy.ansible.com
  version: 3.0.3
- name: community.docker
  source: https://galaxy.ansible.com
  version: 3.12.1
- name: community.general
  source: https://galaxy.ansible.com
  version: 9.3.0
- name: community.grafana
  source: https://galaxy.ansible.com
  version: 1.9.1
- name: community.hashi_vault
  source: https://galaxy.ansible.com
  version: 6.2.0
- name: community.hrobot
  source: https://galaxy.ansible.com
  version: 2.0.1
- name: community.library_inventory_filtering_v1
  source: https://galaxy.ansible.com
  version: 1.0.1
- name: community.libvirt
  source: https://galaxy.ansible.com
  version: 1.3.0
- name: community.mongodb
  source: https://galaxy.ansible.com
  version: 1.7.6
- name: community.mysql
  source: https://galaxy.ansible.com
  version: 3.9.0
- name: community.network
  source: https://galaxy.ansible.com
  version: 5.0.3
- name: community.okd
  source: https://galaxy.ansible.com
  version: 3.0.1
- name: community.postgresql
  source: https://galaxy.ansible.com
  version: 3.4.1
- name: community.proxysql
  source: https://galaxy.ansible.com
  version: 1.6.0
- name: community.rabbitmq
  source: https://galaxy.ansible.com
  version: 1.3.0
- name: community.routeros
  source: https://galaxy.ansible.com
  version: 2.18.0
- name: containers.podman
  source: https://galaxy.ansible.com
  version: 1.15.4
- name: frr.frr
  source: https://galaxy.ansible.com
  version: 2.0.2
- name: google.cloud
  source: https://galaxy.ansible.com
  version: 1.3.0
- name: grafana.grafana
  source: https://galaxy.ansible.com
  version: 5.4.0
- name: hetzner.hcloud
  source: https://galaxy.ansible.com
  version: 3.1.1
- name: kubernetes.core
  source: https://galaxy.ansible.com
  version: 3.2.0
- name: kubevirt.core
  source: https://galaxy.ansible.com
  version: 1.5.0
- name: netbox.netbox
  source: https://galaxy.ansible.com
  version: 3.19.1
- name: ngine_io.cloudstack
  source: https://galaxy.ansible.com
  version: 2.3.0
- name: ngine_io.exoscale
  source: https://galaxy.ansible.com
  version: 1.1.0
- name: openstack.cloud
  source: https://galaxy.ansible.com
  version: 2.2.0
- name: openvswitch.openvswitch
  source: https://galaxy.ansible.com
  version: 2.1.1
- name: ovirt.ovirt
  source: https://galaxy.ansible.com
  version: 3.2.0
- name: vyos.vyos
  source: https://galaxy.ansible.com
  version: 4.1.0
