---
roles:
# From: https://github.com/ansible-community/ansible-build-data/blob/main/2.10/ansible-2.10.7.deps
collections:
#- name: amazon.aws
#  source: https://galaxy.ansible.com
#  version: 1.4.0
- name: ansible.netcommon
  source: https://galaxy.ansible.com
  version: 1.5.0
- name: ansible.posix
  source: https://galaxy.ansible.com
  version: 1.1.1
- name: awx.awx
  source: https://galaxy.ansible.com
  version: 14.1.0
#- name: community.aws
#  source: https://galaxy.ansible.com
#  version: 1.3.0
- name: community.crypto
  source: https://galaxy.ansible.com
  version: 1.4.0
- name: community.digitalocean
  source: https://galaxy.ansible.com
  version: 1.0.0
- name: community.docker
  source: https://galaxy.ansible.com
  version: 1.2.2
- name: community.general
  source: https://galaxy.ansible.com
  version: 1.3.6
- name: community.google
  source: https://galaxy.ansible.com
  version: 1.0.0
- name: community.grafana
  source: https://galaxy.ansible.com
  version: 1.1.0
- name: community.hashi_vault
  source: https://galaxy.ansible.com
  version: 1.1.0
- name: community.kubernetes
  source: https://galaxy.ansible.com
  version: 1.1.1
- name: community.kubevirt
  source: https://galaxy.ansible.com
  version: 1.0.0
- name: community.libvirt
  source: https://galaxy.ansible.com
  version: 1.0.0
- name: community.mongodb
  source: https://galaxy.ansible.com
  version: 1.2.0
- name: community.mysql
  source: https://galaxy.ansible.com
  version: 1.2.0
- name: community.network
  source: https://galaxy.ansible.com
  version: 1.3.2
- name: community.okd
  source: https://galaxy.ansible.com
  version: 1.0.0
- name: community.postgresql
  source: https://galaxy.ansible.com
  version: 1.1.1
- name: community.proxysql
  source: https://galaxy.ansible.com
  version: 1.0.0
- name: community.rabbitmq
  source: https://galaxy.ansible.com
  version: 1.0.1
- name: community.routeros
  source: https://galaxy.ansible.com
  version: 1.1.0
- name: containers.podman
  source: https://galaxy.ansible.com
  version: 1.4.1
- name: frr.frr
  source: https://galaxy.ansible.com
  version: 1.0.3
- name: google.cloud
  source: https://galaxy.ansible.com
  version: 1.0.2
- name: netbox.netbox
  source: https://galaxy.ansible.com
  version: 1.2.1
- name: openstack.cloud
  source: https://galaxy.ansible.com
  version: 1.2.1
- name: openvswitch.openvswitch
  source: https://galaxy.ansible.com
  version: 1.1.0
- name: ovirt.ovirt
  source: https://galaxy.ansible.com
  version: 1.3.0
- name: theforeman.foreman
  source: https://galaxy.ansible.com
  version: 1.5.1
- name: vyos.vyos
  source: https://galaxy.ansible.com
  version: 1.1.1
